# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I am learning jekyll
email: rob@robarnold.io
description: > # this means to ignore newlines until "baseurl:"
  There's nothing to see here, I am just working out the details of how
  to publish on github pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://baz.robarnold.me" # the base hostname & protocol for your site
twitter_username: R0bArnold
github_username:  robarnoldio

# Build settings
markdown: kramdown
